# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/evcharging
spring.datasource.username=root
spring.datasource.password=ali123ali123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Write logs to file
logging.file.name=logs/smart-charging.log

# Still show logs in console
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n

# Optional: set log level
logging.level.com.evgarage.smart_charging=DEBUG

